version: 2.0

defaults: &defaults
  docker:
    - image: circleci/android:api-26-alpha
  working_directory: ~/code
  environment:
    _JAVA_OPTIONS: "-Xmx1400m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
    TERM: dumb

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-22;default;x86" && echo "no" | avdmanager create avd -n Lollipop -k "system-images;android-22;default;x86"
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator -avd Lollipop -noaudio -no-boot-anim -no-window -accel on
          background: false
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies --no-daemon
      - run:
          name: Run tests for debug build and generate reports
          command: ./gradlew testMockDebugUnitTestCoverage --no-daemon
      - run:
          name: Assemble debug APK
          command: ./gradlew assembleDebug --no-daemon
      - run:
          name: Upload reports to Codecov
          command: bash <(curl -s https://codecov.io/bash)
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apks
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - persist_to_workspace:
          root: .
          paths:
            - .gradle
            - build
            - app/build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
